name: calcuaja
description: A Simple Calculator Application in Flutter.
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  function_tree: ^0.8.12
function_tree: ^0.8.12 #added from stack overflow

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
